[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

# Fonts
[".local/share/fonts/noto/Noto_Mono_Nerd_Font_Complete.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Noto/Mono/complete/Noto%20Mono%20Nerd%20Font%20Complete.ttf"

# i3wm themes
[".config/rofi/themes/Dracula1.rasi"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/rofi/master/theme/config1.rasi"
[".config/rofi/themes/Dracula2.rasi"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/rofi/master/theme/config2.rasi"
