config:
  setup_custom_desktop: true

  # Select one or more protocols
  display_protocols:
    - "wayland"

  # Select one or more window managers
  wms:
    - "hyprland"

packages:
  # ---------------------------------------------------------
  # Core & CLI packages
  # ---------------------------------------------------------
  common:
    - git
    - zsh
    - neovim
    - emacs
    - python3
    - nodejs
    - npm
    - fastfetch
    - bat
    - dnsutils
    - htop
    - fzf
    - khal
    - ranger
    - man-db
    - curl
    - tmux
    - starship
    - gdu
    - dust

  # ---------------------------------------------------------
  # GUI / Desktop tools (works on both Wayland and Xorg)
  # ---------------------------------------------------------
  desktop_common:
    - alacritty
    - pipewire
    - pavucontrol
    - playerctl
    - alsa-utils
    - pamixer
    - brightnessctl
    - blueman
    - thunar
    - thunar-volman
    - gvfs
    - xarchiver
    - xreader
    - qalculate-gtk
    - thunderbird
    - font-manager
    - gpick
    - lxappearance
    - python-pywal
    - polkit
    - dunst
    - kitty

  # ---------------------------------------------------------
  # X11-specific setup
  # ---------------------------------------------------------
  desktop_xorg:
    - feh
    - nitrogen
    - rofi
    - dmenu
    - picom
    - polybar
    - redshift
    - flameshot
    - xclip
    - arandr
    - xdotool
    - sxhkd
    - ueberzug
    - sx
    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings

  # ---------------------------------------------------------
  # Wayland-specific setup
  # ---------------------------------------------------------
  desktop_wayland:
    - waybar
    - wofi
    - wl-clipboard
    - swaybg
    - grim
    - slurp
    - wtype
    - gammastep
    - noctalia
    - nwg-displays
    - nwg-look
    - wev

  wm_packages:
    i3wm:
      - i3-wm
      - i3status-rust
    awesome: ["awesome"]
    hyprland:
      - hyprland
      - qt5-wayland
      - qt6-wayland
      - xdg-desktop-portal-hyprland
    qtile:
      - qtile
      - python-psutil
      - python-dbus-next
    dwm: []

  # ---------------------------------------------------------
  # Distro-specific base overrides
  # ---------------------------------------------------------
  distros:
    arch:
      packages:
        - python-pynvim

      aur_packages:
        - j4-dmenu-desktop
        - xfce-polkit

    fedora:
      packages:
        - python3-pynvim
        - NetworkManager-tui
        - xfce-polkit

      replace:
        i3-wm: i3
        qt5-wayland: qt5-qtwayland
        qt6-wayland: qt6-qtwayland
        python-psutil: python3-psutil

