# ----------------------------------------------------------------------
# Nvim
# ----------------------------------------------------------------------

[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

# ----------------------------------------------------------------------
# Fonts
# ----------------------------------------------------------------------

[".local/share/fonts/noto/Noto_Mono_Nerd_Font_Complete.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Noto/Mono/NotoMonoNerdFontMono-Regular.ttf"
[".local/share/fonts/jetbrains/JetBrains_Mono_NL_Regular_Nerd_Font_Complete.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/NoLigatures/Regular/JetBrainsMonoNLNerdFontMono-Regular.ttf"
# Font Awesome
[".local/share/fonts/awesome/Font_Awesome_6_Free_Regular.otf"]
    type= "file"
    url = "https://github.com/FortAwesome/Font-Awesome/raw/6.x/otfs/Font%20Awesome%206%20Free-Regular-400.otf"
[".local/share/fonts/awesome/Font_Awesome_6_Brands_Regular.otf"]
    type= "file"
    url = "https://github.com/FortAwesome/Font-Awesome/raw/6.x/otfs/Font%20Awesome%206%20Brands-Regular-400.otf"
[".local/share/fonts/awesome/Font_Awesome_6_Free_Solid.otf"]
    type= "file"
    url = "https://github.com/FortAwesome/Font-Awesome/raw/6.x/otfs/Font%20Awesome%206%20Free-Solid-900.otf"

# ----------------------------------------------------------------------
# Programs
# ----------------------------------------------------------------------

# Xremap
["bin/"]
    type = "archive"
    url = "https://github.com/k0kubun/xremap/releases/latest/download/xremap-linux-x86_64-x11.zip"
    stripComponents = 0
    refreshPeriod = "168h"
