#!/bin/sh

case $BLOCK_BUTTON in
	1) alacritty --class htop -e htop ;;
	2) notify-send " Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
esac

# Other icon 🧠
free --mebi | sed -n '2{p;q}' | awk '{printf (" %2.2fGiB/%2.2fGiB\n", ( $3 / 1024), ($2 / 1024))}'
