#!/bin/sh

case $BLOCK_BUTTON in
	1) pavucontrol ;;
	2) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
	4) pactl set-sink-volume @DEFAULT_SINK@ +1% ;;
	5) pactl set-sink-volume @DEFAULT_SINK@ -1% ;;
esac

if [ "$(pamixer --get-mute)" = true ]; then
    echo " M"
    exit
fi

vol="$(pamixer --get-volume)"

if [ "$vol" -gt 40 ]; then
    icon=" "
elif [ "$vol" -gt 15 ]; then
    icon=" "
else
    icon=" "
fi

# Edited
[ $? -ne 0 ] && [ -z "$vol" ] && echo "$icon" && exit 1

echo "$icon$vol%"
