#[](#3B4252)\
#[ ](fg:#33658A)

format = """
$character\
[](bg:#3B4252 fg:#3B4252)\
$username$hostname\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$python\
[](fg:#86BBD8 bg:#06969A)\
$nix_shell\
$docker_context\
[](fg:#06969A bg:#33658A)\
[ ](fg:#33658A)\
"""

right_format = """
$cmd_duration\
"""

# Timeout for commands executed by starship
command_timeout = 5000
# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user@]($style)'

[hostname]
disabled = false
ssh_only = false
#format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
style = "bg:#3B4252"
format = '[$hostname $ssh_symbol]($style)'
#trim_at = '.companyname.com'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[cmd_duration]
min_time = 1000
#format = '\[[⏱ $duration]($style)\]'
#format = '[](fg:#434C5E)[](bg:#434C5E fg:#3B4252)[⏱ $duration]($style bg:#3B4252)[](bg:#3B4252 fg:#3B4252)'
format = '[](fg:#3B4252)[ ⏱ $duration]($style bg:#3B4252)[](bg:#3B4252 fg:#3B4252)'

[character]
format = "$symbol"
success_symbol = ""
error_symbol = "[ ✘](bg:#3B4252 fg:#f7768e)"

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
#symbol = ""
style = "bg:#4C566A"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ($virtualenv) ]($style)'

[nix_shell]
symbol = '❆ '
style = "bg:#06969A"
impure_msg = '[impure](bold red)'
pure_msg = '[pure](bold green)'
unknown_msg = '[unknown]($style bold yellow)'
format = '[ $symbol via $state(\($name\)) ]($style)'
heuristic = true

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

